
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  MariaI
 * Created: 18/10/2018
 */

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,      
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CONTATO VARCHAR (100),
    NASC DATE NOT NULL,
    CADASTRO DATE NOT NULL
    /*MINHASACOLA*/ 
);

CREATE TABLE IF NOT EXISTS PRODUTO(
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    MARCA VARCHAR (200) NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR FLOAT NOT NULL
    /*FORNCEDOR (ENUM)*/
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CONTATO VARCHAR(100) NOT NULL
    -- MEUSCLIENTE
);

/*CREATE TABLE IF NOT EXISTS SACOLA(
    ID_SACOLA INT AUTO_INCREMENT PRIMARY KEY,
    QTD INT NOT NULL,
    VALOR_COMPRA DOUBLE NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL, 
    DATA_COMPRA DATE NOT NULL
    -- MINHASACOLA
);*/

-- ALTER TABLE SACOLA ADD CONSTRAINT FK_SACOLA_USUARIO FOREING KEY (ID_USUARIO) REFERENCES CLIENTE (ID_CLIENTE)ON DELETE CASCADE ON UPDATE CASCADE;
-- ALTER TABLE SACOLA ADD CONSTRAINT FK_SACOLA_PRODUTO FOREING KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)ON DELETE CASCADE ON UPDATE CASCADE;
